name: CI-CD Pipeline

on:
  push:
    branches:
      - "feature"
      - "integration"
      - "main"
    paths-ignore: [".github/workflows/**", "README.md"]
  pull_request:
    branches:
      - "integration"
      - "main"
    paths-ignore: [".github/workflows/**", "README.md"]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          export PYTHONPATH=.
          pytest tests/

  sonarqube-sast:
    name: SonarQube SAST Scan
    runs-on: self-hosted
    needs: build-test

    steps:
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://10.0.2.15:9000

  SCA:
    name: SCAN scan (Dependencies)
    runs-on: self-hosted
    needs: sonarqube-sast
    steps:
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true
        
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/checkout@v4
        with:
          python-version: "3.11"
      
      - name: Install pip-audit
        run: |
          sudo apt-get install pipx -y
          pipx ensurepath
          pipx install pip-audit

      - name: Run dependency scan
        run: |
          pip-audit -r requirements.txt
  dast:
    name: DAST Scan (OWASP ZAP)
    runs-on: self-hosted
    needs: SCA   # or deploy-staging depending on where app runs

    steps:
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
          -v $(pwd):/zap/wrk:rw \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py \
          -t http://127.0.0.1:5000 \
          -r zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html


  deploy-dev:
    if: github.ref == 'refs/heads/feature'
    needs: dast
    runs-on: self-hosted
    environment: development
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 10
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'



  deploy-staging:
    if: github.ref == 'refs/heads/integration'
    needs: dast
    runs-on: self-hosted
    environment: staging
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 10
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: dast
    runs-on: self-hosted
    environment: production
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"
  
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 9
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'

