name: CI-CD Pipeline

on:
  push:
    branches:
      - "feature"
      - "integration"
      - "main"
    paths-ignore: [".github/workflows/**", "README.md"]
  pull_request:
    branches:
      - "integration"
      - "main"
    paths-ignore: [".github/workflows/**", "README.md"]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          export PYTHONPATH=.
          pytest tests/

  sonarqube-sast:
    name: SonarQube SAST Scan
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  SCA:
    name: SCAN scan (Dependencies)
    runs-on: ubuntu-latest
    needs: sonarqube-sast
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/checkout@v4
        with:
          python-version: "3.11"
      
      - name: Install pip-audit
        run: |
          pip install pip-audit

      - name: Run dependency scan
        run: |
          pip-audit -r requirements.txt


  deploy-dev:
    if: github.ref == 'refs/heads/feature'
    needs: SCA
    runs-on: ubuntu-latest
    environment: development
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Development environment"

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 10
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'



  deploy-staging:
    if: github.ref == 'refs/heads/integration'
    needs: SCA
    runs-on: ubuntu-latest
    environment: staging
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"
        
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 10
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: SCA
    runs-on: ubuntu-latest
    environment: production
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 9
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'

