name: Feature branch CI

on:
  push:
    branches: [ "feature" ]
    paths-ignore: [".github/workflows/**"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: test
        run: |
          pip install pytest
          export PYTHONPATH=.
          pytest -vv
  Run: 
    environment: development
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: development
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Development environment"

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 10
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'



  deploy-staging:
    if: github.ref == 'refs/heads/integration'
    needs: build-test
    runs-on: ubuntu-latest
    environment: staging
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"
        
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 10
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    environment: production
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run application
        run: |
          python app.py &
          sleep 10
      - name: Test API
        run: |
          curl -X POST http://127.0.0.1:5000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"ci test"}'
